### PR TITLE
Add benchmarks

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by marcinruszkiewicz** [comment]
Oh, benchmarks. I haven't thought of these, nice work. I've tested them locally and they work with two really minor issues:

- You have to run `bundle install` and commit the `Gemfile.lock` as well, since that's what the Travis CI complains about - after adding the lockfile it should pass without issues.
- `bundle exec bench/micro.rb` fails with `bundler: not executable: bench/micro.rb` error, so the file should be commited after running `chmod +x bench/micro.rb`.

@chrisseaton if you can fix these I'll gladly merge it :)

**Comment by chrisseaton** [comment]
Done.

**Comment by chrisseaton** [comment]
Reason for my interest is that I don't often see people using Fiddle, so I've been using it to test how Fiddle works on JRuby and TruffleRuby. Rubinius doesn't support Fiddle so it doesn't work there unfortunately.

**Comment by marcinruszkiewicz** [comment]
Yeah, I saw that using the FFI gem is the common thing, but since this is basically just a toy, I wanted to avoid having too many extra dependencies and learn a thing or two about what else is hiding in the standard Ruby library.

Anyway with the changes all is good, so merging away. Thanks again :)

**Pull request merged**
